language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
    - ~/.npm
branches:
  only:
  - master    
script:
- npm run test  
after_success:
  - npm run travis-deploy-once "npm run semantic-release"