language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
    - ~/.npm
branches:
  only:
  - master    
deploy: 
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
script:
- npm run test:coverage
after_success:
  - npm run report:coverage
  - npm run travis-deploy-once "npm run semantic-release"
  - cd docs
  - npm i
  - npm run deploy